version: '3.7'

volumes:
  redis:

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  api:
    build: ./api
    restart: unless-stopped
    working_dir: /app
    command: yarn dev
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./api:/app
    ports:
      - 3200:3000
      - 3201:9229
    depends_on:
      - redis
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  ui:
    build: ./ui
    restart: unless-stopped
    depends_on:
      - api
    working_dir: /app
    command: yarn dev
    volumes:
      - ./ui:/app
    ports:
      - 3000:1234
      - 3001:3001
    logging:
      options:
        max-size: '10m'
        max-file: '5'
